### ISSUE TITLE
Add new alias for AV85

### ISSUE THREAD

**Issue by jotaylor** [spacetelescope/ullyses-utils#20]
A new alias should be added to catch a FUSE dataset:
OGLE004336.91-732637.7

**Comment by jduval82** [comment]
OGLE J005100.18-725303.9 is the correct alias. OGLE004336.91-732637.7 corresponds to a different star (LHA 115-S 3  aka LIN 48). if OGLE004336.91-732637.7 is the targname of the FUSE dataset then it it not looking at AV 85. 
--


[OGLE](https://cds.unistra.fr/cgi-bin/Dic-Simbad?OGLE) J005100.18-725303.9

**Comment by Rplesha** [comment]
Thanks Julia! It looks like LIN 48 isn't in our sample, so we can close this issue.
