### ISSUE TITLE
Duplicate targets

### ISSUE THREAD

**Issue by sean-lockwood** [spacetelescope/ullyses-utils#26]
@jduval82 -

Reconcile duplicate target rows:
https://github.com/spacetelescope/ullyses-utils/blob/main/utils/data/target_metadata/full_sample_CTTS.xlsx

See rows for `Sz68` and `V505-ORI`.

These are also duplicated in `full_sample_CTTS_for_DB.csv` and likely other downstream files.

**Comment by jduval82** [comment]
@sean-lockwood I just pushed new versions of full_sample_CTTS.xlsx, full_sample_CTTS_for_DB.csv, Lupus_sample_for_website.csv and Sigma Ori_sample_for_website.csv to the update_db_tables branch. I reconciliated the parameters and removed the duplicate row.

**Comment by Rplesha** [comment]
@sean-lockwood I believe this has been resolved. Please feel free to reopen if that is not the case.
